apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: jds-standalone-webpage
spec:
  selector:
    matchLabels:
      app: jds-standalone-webpage
  replicas: 1
  template:
    metadata:
      labels:
        app: jds-standalone-webpage
    spec:
      containers:
        - image: 191518685251.dkr.ecr.us-west-1.amazonaws.com/jds-standalone-webpage:latest
          imagePullPolicy: Always
          name: jds-standalone-webpage
          ports:
            - containerPort: 8889
---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: jds-standalone-webpage-service
spec:
  ports:
    - port: 80
      targetPort: 8889
      protocol: TCP
  type: NodePort
  selector:
    app: jds-standalone-webpage
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: default
  name: jds-standalone-webpage-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-west-1:191518685251:certificate/e361c95f-846b-4026-b15c-2d9d3db80569
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  rules:
    - http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: ssl-redirect
                port:
                  name: use-annotation
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: jds-standalone-webpage-service
                port:
                  number: 80
